import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import WorkProvider from "@/context/WorkProvider";
import Footer from "@/components/shared/Footer";
import { ToastContainer } from "react-toastify";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme='dark'
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      className={`${poppins.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black">

        <WorkProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
          <ToastContainer />
        </WorkProvider>

      </body>
    </html>
  );
}
